# Generated by Django 6.0.7 on 2026-09-10 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('order', models.CharField(choices=[('pairwise_first', 'Design 1 then Design 2'), ('ranking_first', 'Design 2 then Design 1')], default='pairwise_first', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('pairwise', 'Design 1: pairwise choice'), ('ranking', 'Design 2: rank ten'), ('validation', 'Held-out validation')], max_length=16)),
                ('position', models.IntegerField()),
                ('shown', models.TextField()),
                ('ordering', models.TextField()),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='project4.studysession')),
            ],
            options={
                'ordering': ['session', 'block', 'position'],
                'unique_together': {('session', 'block', 'position')},
            },
        ),
    ]
